stages : 
  - install 
  - test 
  - deploy

variables:
  HEROKU_APP_NAME: tp-naruto-zairi

dependencies: 
  stage: install 
  image: node:12-alpine 
  script: 
    - npm install 

test: 
  stage: test 
  image: trion/ng-cli-karma 
  allow_failure: true 
  script: 
    - no install 
    - ng test --progress false --watch false
